// Regenerates (or, with --check, verifies) src/generated/ with the private
// lettermint/sdk-generator. Set LETTERMINT_SDK_GENERATOR to its checkout
// (default: ../sdk-generator next to this repository).
//
// Without the generator (CI, contributors without access), --check only
// verifies that both files carry the generator header with the spec commit
// and hashes, so that hand edits that drop the header are caught.
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src', 'generated');
const check = process.argv.includes('--check');
const generator = resolve(root, process.env.LETTERMINT_SDK_GENERATOR ?? '../sdk-generator');
const available =
  existsSync(join(generator, 'lettermint_sdkgen')) &&
  existsSync(join(generator, 'spec.next.lock.json'));

if (available) {
  const args = [
    '-m',
    'lettermint_sdkgen',
    'emit',
    'typescript',
    '--profile',
    'next',
    '--lock',
    'spec.next.lock.json',
    '--out',
    out,
  ];
  if (check) args.push('--check');
  const result = spawnSync('python3', args, { cwd: generator, stdio: 'inherit' });
  process.exit(result.status ?? 1);
}

if (!check) {
  console.error(
    `The SDK generator was not found at ${generator}. Set LETTERMINT_SDK_GENERATOR to its checkout.`
  );
  process.exit(1);
}

const headers = ['types.ts', 'operations.ts'].map((name) => {
  const lines = readFileSync(join(out, name), 'utf8').split('\n').slice(0, 5);
  const valid =
    lines[0] === '// Generated by lettermint/sdk-generator — do not edit.' &&
    /^\/\/ Spec: lettermint\/lettermint@[0-9a-f]{40}( \(.+\))?$/.test(lines[1]) &&
    /^\/\/ sending-openapi\.json SHA-256: [0-9a-f]{64}$/.test(lines[2]) &&
    /^\/\/ team-openapi\.json SHA-256: [0-9a-f]{64}$/.test(lines[3]) &&
    lines[4] === '// Naming profile: next';
  if (!valid) {
    console.error(
      `src/generated/${name} is missing the generator header. Regenerate it; do not edit it by hand.`
    );
    process.exit(1);
  }
  return lines.join('\n');
});
if (headers[0] !== headers[1]) {
  console.error(
    'src/generated/types.ts and operations.ts come from different specs. Regenerate both.'
  );
  process.exit(1);
}
console.log(`SDK generator not found at ${generator}; checked the generated headers only.`);
console.log(headers[0].split('\n')[1]);
