/* eslint-disable */
// biome-ignore-all lint: generated OpenAPI types use schema-shaped names.
// This file is generated by sdk-generator/node/generate-types.mjs.

export type MessageStatus = "pending" | "queued" | "suppressed" | "processed" | "delivered" | "opened" | "clicked" | "soft_bounced" | "hard_bounced" | "spam_complaint" | "failed" | "blocked" | "policy_rejected" | "unsubscribed";

export interface SendMailRequest {
  "route"?: string;
  "from": string;
  "subject": string;
  "tag"?: string | null;
  "html"?: string | null;
  "text"?: string | null;
  "to": string[];
  "cc"?: string[];
  "bcc"?: string[];
  "reply_to"?: string[];
  "headers"?: Record<string, string>;
  "metadata"?: Record<string, string>;
  "settings"?: {
  "track_opens"?: boolean;
  "track_clicks"?: boolean;
} | null;
  "attachments"?: {
  "filename": string;
  "content": string;
  "content_type"?: string | null;
  "content_id"?: string | null;
}[];
}

export type SendBatchMailRequest = {
  "route"?: string;
  "from": string;
  "to": string[];
  "cc"?: string[];
  "bcc"?: string[];
  "reply_to"?: string[];
  "subject": string;
  "headers"?: Record<string, string>;
  "metadata"?: Record<string, string>;
  "tag"?: string | null;
  "settings"?: {
  "track_opens"?: boolean;
  "track_clicks"?: boolean;
} | null;
  "html"?: string | null;
  "text"?: string | null;
  "attachments"?: {
  "filename": string;
  "content": string;
  "content_type"?: string | null;
  "content_id"?: string | null;
}[];
}[];

export type AttachmentDelivery = "inline" | "url";

export type DnsRecordStatus = "active" | "failed" | "pending";

export interface DomainData {
  "id": string;
  "domain": string;
  "status_changed_at": string | null;
  "dns_records"?: DomainDnsRecordData[];
  "projects"?: {
  "id": string;
  "name": string;
}[];
  "created_at": string;
}

export interface DomainDnsRecordData {
  "id": string;
  "type": RecordType;
  "hostname": string;
  "fqdn": string;
  "content": string;
  "status": DnsRecordStatus;
  "verified_at": string | null;
  "last_checked_at": string | null;
}

export interface DomainListData {
  "id": string;
  "domain": string;
  "status": DomainStatus;
  "status_changed_at": string | null;
  "created_at": string;
}

export type DomainStatus = "verified" | "partially_verified" | "pending_verification" | "failed_verification";

export type InitialRoutes = "both" | "transactional" | "broadcast";

export interface MessageAttachmentData {
  "size": number;
  "filename": string;
  "content_id": string | null;
  "content_type": string;
}

export interface MessageData {
  "id": string;
  "type": MessageType;
  "status": MessageStatus;
  "status_changed_at": string | null;
  "tag": string | null;
  "from_email": string;
  "from_name": string | null;
  "reply_to": string[] | null;
  "subject": string | null;
  "to": MessageRecipientData[] | null;
  "cc": MessageRecipientData[] | null;
  "bcc": MessageRecipientData[] | null;
  "attachments": MessageAttachmentData[] | null;
  "metadata": Record<string, string> | null;
  "spam_score"?: number | null;
  "spam_symbols"?: SpamSymbol[];
  "route_id": string;
  "created_at": string;
}

export interface MessageEventData {
  "message_id": string;
  "event": MessageEventType;
  "metadata": Record<string, unknown> | null;
  "timestamp": string;
}

export type MessageEventType = "queued" | "processed" | "suppressed" | "delivered" | "soft_bounced" | "hard_bounced" | "spam_complaint" | "failed" | "blocked" | "policy_rejected" | "unsubscribed" | "opened" | "clicked" | "inbound_received" | "inbound_queued" | "inbound_spam_blocked" | "inbound_processed" | "inbound_retry";

export interface MessageListData {
  "id": string;
  "type": MessageType;
  "status": MessageStatus;
  "from_email": string;
  "from_name": string | null;
  "subject": string | null;
  "to": MessageRecipientData[] | null;
  "cc": MessageRecipientData[] | null;
  "bcc": MessageRecipientData[] | null;
  "reply_to": string[] | null;
  "tag": string | null;
  "created_at": string;
}

export interface MessageRecipientData {
  "email": string;
  "name": string | null;
}

export interface MessageStatsData {
  "messages_transactional": number;
  "messages_broadcast": number;
  "messages_inbound": number;
  "deliverability": number;
}

export type MessageType = "inbound" | "outbound";

export type Plan = "free" | "starter" | "growth" | "pro";

export interface ProjectData {
  "id": string;
  "name": string;
  "smtp_enabled": boolean;
  "default_route_id": string | null;
  "token_generated_at": string | null;
  "token_last_used_at": string | null;
  "token_last_used_ip": string | null;
  "routes"?: RouteData[];
  "routes_count"?: number;
  "domains"?: DomainData[];
  "domains_count"?: number;
  "team_members"?: TeamMemberData[];
  "team_members_count"?: number;
  "last_28_days"?: MessageStatsData | unknown;
  "created_at": string;
  "updated_at": string;
}

export interface ProjectListData {
  "id": string;
  "name": string;
  "smtp_enabled": boolean;
  "routes_count": number;
  "domains_count": number;
  "team_members_count": number;
  "last_28_days": MessageStatsData;
  "created_at": string;
  "updated_at": string;
}

export type RecordType = "TXT" | "CNAME" | "MX";

export interface RouteData {
  "id": string;
  "project_id": string;
  "slug": string;
  "name": string;
  "route_type": RouteType;
  "is_default": boolean;
  "inbound_address"?: string;
  "inbound_domain"?: string;
  "inbound_domain_verified_at"?: string;
  "inbound_spam_threshold"?: number;
  "attachment_delivery"?: AttachmentDelivery;
  "project"?: ProjectData;
  "webhooks_count"?: number;
  "suppressed_recipients_count"?: number;
  "statistics"?: {
} | RouteStatisticData[];
  "created_at": string;
  "updated_at": string;
}

export interface RouteListData {
  "id": string;
  "slug": string;
  "name": string;
  "route_type": RouteType;
  "is_default": boolean;
  "webhooks_count": number;
  "suppressed_recipients_count": number;
  "created_at": string;
  "updated_at": string;
}

export interface RouteStatisticData {
  "date": string;
  "sent_count": number;
  "delivered_count": number;
  "opened_count": number;
  "clicked_count": number;
  "hard_bounce_count": number;
  "spam_complaint_count": number;
  "inbound_received_count": number;
  "effective_opened_count": number | null;
  "machine_opened_count": number | null;
  "machine_clicked_count": number | null;
}

export type RouteType = "transactional" | "broadcast" | "inbound";

export interface SpamSymbol {
  "name": string;
  "score": number;
  "options": string[];
  "description": string | null;
}

export interface StatsDailyData {
  "date": string;
  "sent": number;
  "delivered": number;
  "hard_bounced": number;
  "spam_complaints": number;
  "opened": number | null;
  "clicked": number | null;
  "inbound": StatsInboundData;
  "transactional": StatsTypeData | unknown;
  "broadcast": StatsTypeData | unknown;
  "effective_opened": number | null;
  "machine_opened": number | null;
  "machine_clicked": number | null;
}

export interface StatsData {
  "from": string;
  "to": string;
  "totals": StatsTotalsData;
  "daily": StatsDailyData[];
}

export interface StatsInboundData {
  "received": number;
}

export interface StatsRequestData {
  "from": string;
  "to": string;
  "project_id"?: string | null;
  "include_machine"?: boolean;
}

export interface StatsTotalsData {
  "sent": number;
  "delivered": number;
  "hard_bounced": number;
  "spam_complaints": number;
  "opened": number | null;
  "clicked": number | null;
  "inbound": StatsInboundData;
  "transactional": StatsTypeData | unknown;
  "broadcast": StatsTypeData | unknown;
  "effective_opened": number | null;
  "machine_opened": number | null;
  "machine_clicked": number | null;
}

export interface StatsTypeData {
  "sent": number;
  "hard_bounced": number;
  "spam_complaints": number;
}

export interface StoreDomainData {
  "domain": string;
}

export interface StoreProjectData {
  "name": string;
  "smtp_enabled"?: boolean;
  "initial_routes"?: InitialRoutes;
}

export interface StoreRouteData {
  "name": string;
  "route_type": RouteType;
  "slug"?: string | null;
}

export interface StoreSuppressionData {
  "email"?: string | null;
  "reason": SuppressionReason;
  "scope": "team" | "project" | "route";
  "route_id"?: string | null;
  "project_id"?: string | null;
  "emails"?: string[] | null;
}

export interface StoreWebhookData {
  "route_id": string;
  "name": string;
  "url": string;
  "enabled"?: boolean | null;
  "include_machine_events"?: boolean | null;
  "events": WebhookEvent[];
}

export interface SuppressedRecipientData {
  "id": string;
  "type": SuppressionType;
  "value": string;
  "reason": SuppressionReason;
  "scope": SuppressionScope;
  "project_id": string | null;
  "route_id": string | null;
  "created_at": string;
  "updated_at": string;
}

export type SuppressionReason = "spam_complaint" | "hard_bounce" | "unsubscribe" | "manual";

export type SuppressionScope = "global" | "team" | "project" | "route";

export type SuppressionType = "email" | "domain" | "extension";

export interface TeamAddonData {
  "type": string | null;
  "expires_at": string | null;
}

export interface TeamData {
  "id": string;
  "name": string;
  "type": TeamType;
  "plan": Plan;
  "tier": VolumeTier;
  "verified_at": string | null;
  "features"?: string[];
  "addons"?: TeamAddonData[];
  "created_at": string;
  "domains_count"?: number;
  "projects_count"?: number;
  "members_count"?: number;
}

export interface TeamMemberData {
  "id": string;
  "user"?: UserData;
  "role": string | null;
  "joined_at": string | null;
}

export type TeamType = "personal" | "business";

export interface TeamUsageDetailData {
  "current_period": TeamUsagePeriodData;
  "historical_usage": TeamUsagePeriodData[];
}

export interface TeamUsagePeriodData {
  "usage": number;
  "last_incremented_at": string | null;
  "period_start": string;
  "period_end": string;
}

export interface UpdateDomainProjectsData {
  "project_ids": string[];
}

export interface UpdateProjectData {
  "name"?: string | null;
  "smtp_enabled"?: boolean | null;
  "default_route_id"?: string | null;
}

export interface UpdateProjectMembersData {
  "team_member_ids": string[];
}

export interface UpdateRouteData {
  "name"?: string | null;
  "settings"?: {
  "track_opens"?: boolean | null;
  "track_clicks"?: boolean | null;
  "disable_hosted_unsubscribe"?: boolean | null;
};
  "inbound_settings"?: {
  "inbound_domain"?: string | null;
  "inbound_spam_threshold"?: number | null;
  "attachment_delivery"?: AttachmentDelivery;
};
}

export interface UpdateTeamData {
  "name"?: string | null;
}

export interface UpdateWebhookData {
  "name"?: string;
  "url"?: string;
  "enabled"?: boolean;
  "include_machine_events"?: boolean;
  "events"?: WebhookEvent[];
}

export interface UserData {
  "id": string;
  "name": string;
  "email": string;
  "avatar": string | null;
}

export type VolumeTier = 300 | 10000 | 50000 | 125000 | 500000 | 750000 | 1000000 | 1500000;

export interface WebhookData {
  "id": string;
  "route_id": string;
  "name": string;
  "url": string;
  "events": string[];
  "enabled": boolean;
  "include_machine_events": boolean;
  "secret"?: string;
  "last_called_at": string | null;
  "created_at": string;
  "updated_at": string;
}

export interface WebhookDeliveryData {
  "id": string;
  "webhook_id": string;
  "event_type": WebhookEvent;
  "status": WebhookDeliveryStatus;
  "attempt_number": number;
  "http_status_code": number | null;
  "duration_ms": number | null;
  "payload": string[];
  "response_body": string | null;
  "response_headers": string[] | null;
  "error_message": string | null;
  "delivered_at": string | null;
  "timestamp": string;
}

export interface WebhookDeliveryListData {
  "id": string;
  "webhook_id": string;
  "event_type": WebhookEvent;
  "status": WebhookDeliveryStatus;
  "attempt_number": number;
  "http_status_code": number | null;
  "duration_ms": number | null;
  "delivered_at": string | null;
  "created_at": string;
}

export type WebhookDeliveryStatus = "pending" | "success" | "failed" | "client_error" | "server_error" | "timeout";

export type WebhookEvent = "message.created" | "message.sent" | "message.delivered" | "message.hard_bounced" | "message.soft_bounced" | "message.spam_complaint" | "message.failed" | "message.suppressed" | "message.unsubscribed" | "message.opened" | "message.clicked" | "message.inbound" | "message.policy_rejected" | "webhook.test";

export interface WebhookListData {
  "id": string;
  "route_id": string;
  "name": string;
  "url": string;
  "events": WebhookEvent[];
  "enabled": boolean;
  "last_called_at": string | null;
  "created_at": string;
  "updated_at": string;
}

export type EmailPayload = SendMailRequest;
export type SendEmailResponse = SendMailResponse;
export type SendBatchEmailResponse = SendBatchMailResponse;
export type SendMailResponse = {
  "message_id": string;
  "status": MessageStatus;
};
export type SendBatchMailResponse = {
  "message_id": string;
  "status": MessageStatus;
}[];
export type PingResponse = 200;
export type DomainIndexResponse = {
  "data": DomainListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type DomainStoreRequest = StoreDomainData;
export type DomainStoreResponse = DomainData;
export type DomainShowResponse = DomainData;
export type DomainDestroyResponse = {
  "message": "Domain deleted successfully.";
};
export type DomainVerifyDnsRecordsResponse = {
  "message": string;
};
export type DomainVerifySpecificDnsRecordResponse = {
  "message": "DNS record verified successfully.";
};
export type DomainUpdateProjectsRequest = UpdateDomainProjectsData;
export type DomainUpdateProjectsResponse = {
  "data": DomainData;
  "message": "Domain projects updated successfully.";
};
export type MessageIndexResponse = {
  "data": MessageListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
} | MessageListData[];
export type MessageShowResponse = MessageData;
export type MessageEventsResponse = {
  "data": MessageEventData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type ProjectIndexResponse = {
  "data": ProjectListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type ProjectStoreRequest = StoreProjectData;
export type ProjectStoreResponse = {
  "data": ProjectData;
  "message": "Project created successfully.";
  "api_token": string;
};
export type ProjectShowResponse = ProjectData;
export type ProjectUpdateRequest = UpdateProjectData;
export type ProjectUpdateResponse = {
  "data": ProjectData;
  "message": "Project updated successfully.";
};
export type ProjectDestroyResponse = {
  "message": "Project deleted successfully.";
};
export type ProjectRotateTokenResponse = {
  "data": ProjectData;
  "new_token": string;
  "message": "API token rotated successfully. Please update your integrations.";
};
export type ProjectUpdateMembersRequest = UpdateProjectMembersData;
export type ProjectUpdateMembersResponse = {
  "data": ProjectData;
  "message": "Project members updated successfully.";
};
export type ProjectAddMemberResponse = {
  "message": "Team member added to project successfully.";
};
export type ProjectRemoveMemberResponse = {
  "message": "Team member removed from project successfully.";
};
export type RouteIndexResponse = {
  "data": RouteListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type RouteStoreRequest = StoreRouteData;
export type RouteStoreResponse = {
  "data": RouteData;
  "message": "Route created successfully.";
};
export type RouteShowResponse = RouteData;
export type RouteUpdateRequest = UpdateRouteData;
export type RouteUpdateResponse = {
  "data": RouteData;
  "message": "Route updated successfully.";
};
export type RouteDestroyResponse = {
  "message": "Route deleted successfully.";
};
export type RouteVerifyInboundDomainResponse = {
  "data": {
  "verified": boolean;
  "message": "Inbound domain verified successfully.";
};
};
export type StatsIndexResponse = StatsData;
export type SuppressionIndexResponse = {
  "data": SuppressedRecipientData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type SuppressionStoreRequest = StoreSuppressionData;
export type SuppressionStoreResponse = {
  "message": string | "No emails were added.";
  "data": {
  "created": string[];
  "skipped": string[];
};
};
export type SuppressionDestroyResponse = {
  "message": "Email removed from suppression list successfully.";
};
export type TeamShowResponse = TeamData;
export type TeamUpdateRequest = UpdateTeamData;
export type TeamUpdateResponse = {
  "data": TeamData;
  "message": "Team settings updated successfully.";
};
export type TeamUsageResponse = TeamUsageDetailData;
export type TeamMembersResponse = {
  "data": TeamMemberData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type WebhookIndexResponse = {
  "data": WebhookListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type WebhookStoreRequest = StoreWebhookData;
export type WebhookStoreResponse = {
  "data": WebhookData;
  "message": "Webhook created successfully. Please save the secret as it will not be shown again.";
};
export type WebhookShowResponse = WebhookData;
export type WebhookUpdateRequest = UpdateWebhookData;
export type WebhookUpdateResponse = {
  "data": WebhookData;
  "message": "Webhook updated successfully.";
};
export type WebhookDestroyResponse = {
  "message": "Webhook deleted successfully.";
};
export type WebhookTestResponse = {
  "message": "Test webhook dispatched successfully. Check the deliveries endpoint for results.";
  "delivery_id": string;
};
export type WebhookRegenerateSecretResponse = {
  "data": WebhookData;
  "message": "Webhook secret regenerated successfully. Please update your integration.";
};
export type WebhookDeliveriesResponse = {
  "data": WebhookDeliveryListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type WebhookShowDeliveryResponse = WebhookDeliveryData;
