/* eslint-disable */
// biome-ignore-all lint: generated OpenAPI types use schema-shaped names.
// This file is generated by sdk-generator/node/generate-types.mjs.

export type MessageStatus = "scheduled" | "pending" | "queued" | "quarantined" | "suppressed" | "processed" | "delivered" | "opened" | "clicked" | "soft_bounced" | "hard_bounced" | "spam_complaint" | "failed" | "blocked" | "policy_rejected" | "unsubscribed" | "canceled";

/** A reusable exact-match message tag. */
export interface MessageTag {
  "name": string;
  "value": string;
}

export interface SendMailRequest {
  "route"?: string;
  "from": string;
  "to": string[];
  "cc"?: string[];
  "bcc"?: string[];
  "reply_to"?: string[];
  "subject": string;
  "scheduled_at"?: string;
  "headers"?: Record<string, string>;
  "metadata"?: Record<string, string>;
  "tag"?: string | null;
  "tags"?: MessageTag[];
  "settings"?: {
  "track_opens"?: boolean;
  "track_clicks"?: boolean;
  "tls"?: TlsPolicy;
};
  "html"?: string | null;
  "text"?: string | null;
  "attachments"?: {
  "filename": string;
  "content": string;
  "content_type"?: string | null;
  "content_id"?: string | null;
}[];
  "sandbox_result"?: SandboxResult;
}

export type SendBatchMailRequest = {
  "route"?: string;
  "from": string;
  "to": string[];
  "cc"?: string[];
  "bcc"?: string[];
  "reply_to"?: string[];
  "subject": string;
  "scheduled_at"?: string;
  "headers"?: Record<string, string>;
  "metadata"?: Record<string, string>;
  "tag"?: string | null;
  "tags"?: MessageTag[];
  "settings"?: {
  "track_opens"?: boolean;
  "track_clicks"?: boolean;
  "tls"?: TlsPolicy;
};
  "html"?: string | null;
  "text"?: string | null;
  "attachments"?: {
  "filename": string;
  "content": string;
  "content_type"?: string | null;
  "content_id"?: string | null;
}[];
  "sandbox_result"?: SandboxResult;
}[];

export type TlsPolicy = "opportunistic" | "enforced";

export type SandboxResult = "delivered" | "hard_bounced" | "soft_bounced" | "deferred" | "failed" | "suppressed" | "spam_complaint" | "auto_replied" | "opened" | "clicked" | "unsubscribed";

export type AttachmentDelivery = "inline" | "url";

export type BuiltInTeamRole = "owner" | "admin" | "member";

export interface CursorPaginator {
  "data": string[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
}

export type DkimMode = "legacy_txt" | "managed_cname";

export type DnsRecordPurpose = "return_path" | "dmarc" | "dkim_legacy" | "dkim_primary" | "dkim_secondary";

export type DnsRecordStatus = "active" | "failed" | "pending";

export type DnsVerificationScope = "required" | "recommended" | "migration" | "deprecated";

export interface DomainData {
  "id": string;
  "domain": string;
  "dkim_mode": DkimMode;
  "rotation_ready": boolean;
  "status_changed_at": string | null;
  "dns_records"?: DomainDnsRecordData[];
  "projects"?: {
  "id": string;
  "name": string;
}[];
  "created_at": string;
}

export interface DomainDnsRecordData {
  "id": string;
  "type": RecordType;
  "hostname": string;
  "fqdn": string;
  "content": string;
  "status": DnsRecordStatus;
  "purpose": DnsRecordPurpose;
  "verification_scope": DnsVerificationScope;
  "required_for_verification": boolean;
  "verified_at": string | null;
  "last_checked_at": string | null;
}

export interface DomainListData {
  "id": string;
  "domain": string;
  "status": DomainStatus;
  "dkim_mode": DkimMode;
  "status_changed_at": string | null;
  "created_at": string;
}

export type DomainStatus = "verified" | "partially_verified" | "pending_verification" | "failed_verification";

export type InitialRoutes = "both" | "transactional" | "broadcast";

export interface MessageAttachmentData {
  "size": number;
  "filename": string;
  "content_id": string | null;
  "content_type": string;
}

export interface MessageData {
  "id": string;
  "type": MessageType;
  "status": MessageStatus;
  "status_changed_at": string | null;
  "scheduled_at": string | null;
  "tag": string | null;
  "tags": MessageTag[];
  "from_email": string;
  "from_name": string | null;
  "reply_to": string[] | null;
  "subject": string | null;
  "to": MessageRecipientData[] | null;
  "cc": MessageRecipientData[] | null;
  "bcc": MessageRecipientData[] | null;
  "attachments": MessageAttachmentData[] | null;
  "metadata": Record<string, string> | null;
  "spam_score"?: number | null;
  "spam_symbols"?: SpamSymbol[];
  "route_id": string;
  "created_at": string;
  "delivery_mode": DeliveryMode;
  "sandbox_result": SandboxResult | null;
}

export interface MessageEventData {
  "message_id": string;
  "event": MessageEventType;
  "tag": string | null;
  "tags": MessageTag[];
  "metadata": Record<string, unknown> | null;
  "timestamp": string;
}

export type MessageEventType = "scheduled" | "rescheduled" | "canceled" | "released" | "queued" | "processed" | "suppressed" | "delivered" | "auto_replied" | "soft_bounced" | "hard_bounced" | "spam_complaint" | "failed" | "blocked" | "policy_rejected" | "unsubscribed" | "opened" | "clicked" | "inbound_received" | "inbound_queued" | "inbound_spam_blocked" | "inbound_released" | "inbound_processed" | "inbound_retry";

export interface MessageListData {
  "id": string;
  "type": MessageType;
  "status": MessageStatus;
  "scheduled_at": string | null;
  "spam_score"?: number | null;
  "from_email": string;
  "from_name": string | null;
  "subject": string | null;
  "to": MessageRecipientData[] | null;
  "cc": MessageRecipientData[] | null;
  "bcc": MessageRecipientData[] | null;
  "reply_to": string[] | null;
  "tag": string | null;
  "tags": MessageTag[];
  "status_changed_at": string | null;
  "created_at": string;
  "delivery_mode": DeliveryMode;
  "sandbox_result": SandboxResult | null;
}

export interface MessageRecipientData {
  "email": string;
  "name": string | null;
  "sandbox_result": SandboxResult | null;
}

export interface MessageStatsData {
  "messages_transactional": number;
  "messages_broadcast": number;
  "messages_inbound": number;
  "deliverability": number;
}

export type MessageType = "inbound" | "outbound";

export type Plan = "free" | "starter" | "growth" | "pro";

export type ProjectAccessScope = "all" | "selected";

export interface ProjectData {
  "id": string;
  "name": string;
  "smtp_enabled": boolean;
  "redact_email_content": boolean;
  "default_route_id": string | null;
  "token_generated_at": string | null;
  "token_last_used_at": string | null;
  "token_last_used_ip": string | null;
  "routes"?: RouteData[];
  "routes_count"?: number;
  "domains"?: DomainData[];
  "domains_count"?: number;
  "last_28_days"?: MessageStatsData | null;
  "created_at": string;
  "updated_at": string;
  "delivery_mode": DeliveryMode;
}

export interface ProjectListData {
  "id": string;
  "name": string;
  "delivery_mode": DeliveryMode;
  "smtp_enabled": boolean;
  "routes_count": number;
  "domains_count": number;
  "last_28_days": MessageStatsData;
  "created_at": string;
  "updated_at": string;
}

export type RbacConflictCode = "stale_resource" | "owner_protected" | "last_owner" | "built_in_role_immutable" | "custom_role_requires_pro";

export type RbacPermission = "team:manage" | "billing:manage" | "security:manage" | "audit:read" | "support:manage" | "members:read" | "members:manage" | "roles:manage" | "team_tokens:read" | "team_tokens:manage" | "team_tokens:rotate" | "team_tokens:revoke" | "projects:create" | "team_suppressions:read" | "team_suppressions:add" | "team_suppressions:remove" | "projects:read" | "projects:manage" | "projects:delete" | "routes:read" | "routes:manage" | "routes:delete" | "domains:read" | "domains:manage" | "domains:delete" | "project_tokens:read" | "project_tokens:manage" | "project_tokens:rotate" | "project_tokens:revoke" | "webhooks:read" | "webhooks:manage" | "webhooks:delete" | "webhooks:rotate_secret" | "stats:read" | "analytics:read" | "messages:read" | "messages:read_content" | "messages:send" | "suppressions:read" | "suppressions:add" | "suppressions:remove";

export type RecordType = "TXT" | "CNAME" | "MX";

export interface RescheduleMessageRequest {
  "scheduled_at": string;
}

export interface RouteData {
  "id": string;
  "project_id": string;
  "slug": string;
  "name": string;
  "route_type": RouteType;
  "is_default": boolean;
  "inbound_address"?: string | null;
  "inbound_mx_hostname"?: string;
  "inbound_route_domain"?: string | null;
  "inbound_domain"?: string | null;
  "inbound_domain_verified_at"?: string | null;
  "inbound_spam_threshold"?: number | null;
  "attachment_delivery"?: AttachmentDelivery;
  "settings"?: {
  "disable_hosted_unsubscribe"?: boolean;
  "track_opens"?: boolean;
  "track_clicks"?: boolean;
  "generate_plaintext_fallback"?: boolean;
  "suppress_auto_responders"?: boolean;
  "suppress_disposable_recipients"?: boolean;
  "tls"?: TlsPolicy;
  "redact_email_content"?: boolean;
  "attachment_delivery"?: {
};
} | null;
  "project"?: ProjectData;
  "webhooks_count"?: number;
  "suppressed_recipients_count"?: number;
  "statistics"?: RouteStatisticData[];
  "created_at": string;
  "updated_at": string;
}

export interface RouteListData {
  "id": string;
  "slug": string;
  "name": string;
  "route_type": RouteType;
  "is_default": boolean;
  "webhooks_count": number;
  "suppressed_recipients_count": number;
  "created_at": string;
  "updated_at": string;
}

export interface RouteStatisticData {
  "date": string;
  "sent_count": number;
  "delivered_count": number;
  "opened_count": number;
  "clicked_count": number;
  "hard_bounce_count": number;
  "spam_complaint_count": number;
  "inbound_received_count": number;
  "observed_opened_count"?: number | null;
  "human_opened_count"?: number | null;
  "privacy_opened_count"?: number | null;
  "effective_opened_count": number | null;
  "machine_opened_count": number | null;
  "machine_clicked_count": number | null;
}

export type RouteType = "transactional" | "broadcast" | "inbound";

export interface SpamSymbol {
  "name": string;
  "score": number;
  "options": string[];
  "description": string | null;
}

export interface StatsDailyData {
  "date": string;
  "sent": number;
  "delivered": number;
  "hard_bounced": number;
  "spam_complaints": number;
  "opened": number | null;
  "clicked": number | null;
  "inbound": StatsInboundData;
  "transactional": StatsTypeData | null;
  "broadcast": StatsTypeData | null;
  "observed_opened"?: number | null;
  "human_opened"?: number | null;
  "privacy_opened"?: number | null;
  "effective_opened": number | null;
  "machine_opened": number | null;
  "machine_clicked": number | null;
}

export interface StatsData {
  "from": string;
  "to": string;
  "totals": StatsTotalsData;
  "daily": StatsDailyData[];
}

export interface StatsInboundData {
  "received": number;
}

export interface StatsRequestData {
  "from": string;
  "to": string;
  "project_id"?: string | null;
  "include_machine"?: boolean;
}

export interface StatsTotalsData {
  "sent": number;
  "delivered": number;
  "hard_bounced": number;
  "spam_complaints": number;
  "opened": number | null;
  "clicked": number | null;
  "inbound": StatsInboundData;
  "transactional": StatsTypeData | null;
  "broadcast": StatsTypeData | null;
  "observed_opened"?: number | null;
  "human_opened"?: number | null;
  "privacy_opened"?: number | null;
  "effective_opened": number | null;
  "machine_opened": number | null;
  "machine_clicked": number | null;
}

export interface StatsTypeData {
  "sent": number;
  "hard_bounced": number;
  "spam_complaints": number;
}

export interface StoreDomainData {
  "domain": string;
}

export interface StoreProjectData {
  "name": string;
  "smtp_enabled"?: boolean;
  "delivery_mode"?: DeliveryMode;
  "initial_routes"?: InitialRoutes;
  "short_token"?: boolean;
  "redact_email_content"?: boolean;
}

export interface StoreRouteData {
  "name": string;
  "route_type": RouteType;
  "slug"?: string | null;
  "settings"?: UpdateRouteSettingsData | null;
  "inbound_settings"?: UpdateRouteInboundSettingsData | null;
  "inbound_domain"?: string | null;
  "inbound_spam_threshold"?: number | null;
  "attachment_delivery"?: AttachmentDelivery | null;
}

export interface StoreSuppressionData {
  "email"?: string | null;
  "emails"?: string[] | null;
  "reason": SuppressionReason;
  "scope": SuppressionScope;
  "route_id"?: string | null;
  "project_id"?: string | null;
  "applies_to"?: SuppressionAppliesTo | null;
}

export interface StoreWebhookData {
  "name": string;
  "url": string;
  "events": WebhookEvent[];
  "enabled"?: boolean | null;
  "include_machine_events"?: boolean | null;
  "scope"?: WebhookScope | null;
  "project_ids"?: string[];
  "route_ids"?: string[];
  "route_id"?: string | null;
  "delivery_mode_filter"?: WebhookDeliveryModeFilter | null;
}

export interface SuppressedRecipientData {
  "id": string;
  "type": SuppressionType;
  "value": string;
  "reason": SuppressionReason;
  "scope": SuppressionScope;
  "applies_to": SuppressionAppliesTo;
  "project_id": string | null;
  "route_id": string | null;
  "source_message"?: SuppressionSourceMessageData | null;
  "created_at": string;
}

export type SuppressionAppliesTo = "all" | "broadcast";

export type SuppressionReason = "spam_complaint" | "hard_bounce" | "unsubscribe" | "manual";

export type SuppressionScope = "team" | "project" | "route";

export interface SuppressionSourceMessageData {
  "id": string;
  "available": boolean;
  "subject": string | null;
  "created_at": string | null;
}

export type SuppressionType = "email" | "domain" | "extension";

export interface TeamAddonData {
  "type": string | null;
  "expires_at": string | null;
}

export interface TeamData {
  "id": string;
  "name": string;
  "type": TeamType;
  "plan": Plan;
  "included_volume": number;
  "tier": number;
  "verified_at": string | null;
  "features"?: string[];
  "addons"?: TeamAddonData[];
  "created_at": string;
  "domains_count"?: number;
  "projects_count"?: number;
  "members_count"?: number;
}

export interface TeamMemberData {
  "id": string;
  "name": string;
  "email": string;
  "role": {
  "id": string;
  "name": string;
};
  "project_access": TeamMemberProjectAccessData;
  "joined_at": string | null;
}

export interface TeamMemberProjectAccessData {
  "scope": ProjectAccessScope;
  "projects": {
  "id": string;
  "name": string;
}[];
}

export interface TeamRoleData {
  "id": string;
  "name": string;
  "system_key": BuiltInTeamRole | null;
  "permissions": RbacPermission[];
  "assignable": boolean;
}

export type TeamType = "personal" | "business";

export interface TeamUsageDetailData {
  "current_period": TeamUsagePeriodData;
  "historical_usage": TeamUsagePeriodData[];
}

export interface TeamUsagePeriodData {
  "usage": number;
  "last_incremented_at": string | null;
  "period_start": string;
  "period_end": string;
}

export interface UpdateDomainProjectsData {
  "project_ids": string[];
}

export interface UpdateProjectData {
  "name"?: string | null;
  "smtp_enabled"?: boolean | null;
  "redact_email_content"?: boolean | null;
  "default_route_id"?: string | null;
  "delivery_mode"?: DeliveryMode | null;
}

export interface UpdateRouteData {
  "name"?: string | null;
  "settings"?: UpdateRouteSettingsData | null;
  "inbound_settings"?: UpdateRouteInboundSettingsData | null;
  "inbound_domain"?: string | null;
  "inbound_spam_threshold"?: number | null;
  "attachment_delivery"?: AttachmentDelivery | null;
}

export interface UpdateRouteInboundSettingsData {
  "inbound_domain"?: string | null;
  "inbound_spam_threshold"?: number | null;
  "attachment_delivery"?: AttachmentDelivery | null;
}

export interface UpdateRouteSettingsData {
  "track_opens"?: boolean | null;
  "track_clicks"?: boolean | null;
  "generate_plaintext_fallback"?: boolean | null;
  "suppress_auto_responders"?: boolean | null;
  "suppress_disposable_recipients"?: boolean | null;
  "tls"?: TlsPolicy | null;
  "disable_hosted_unsubscribe"?: boolean | null;
  "redact_email_content"?: boolean | null;
}

export interface UpdateTeamData {
  "name"?: string;
}

export interface UpdateTeamMemberAssignmentData {
  "role_id": string;
  "project_access": {
  "scope": ProjectAccessScope;
  "project_ids"?: string[];
};
}

export interface UpdateWebhookData {
  "name"?: string;
  "url"?: string;
  "events"?: WebhookEvent[];
  "enabled"?: boolean;
  "include_machine_events"?: boolean;
  "scope"?: WebhookScope;
  "project_ids"?: string[];
  "route_ids"?: string[];
  "route_id"?: string | null;
  "delivery_mode_filter"?: WebhookDeliveryModeFilter;
}

export interface WebhookData {
  "id": string;
  "scope": WebhookScope;
  "project_ids": string[];
  "route_ids": string[];
  "route_id": string | null;
  "name": string;
  "url": string;
  "events": string[];
  "enabled": boolean;
  "include_machine_events": boolean;
  "last_called_at": string | null;
  "created_at": string;
  "updated_at": string;
  "delivery_mode_filter": WebhookDeliveryModeFilter;
}

export interface WebhookDeliveryData {
  "id": string;
  "webhook_id": string;
  "event_type": WebhookEvent;
  "source_scope": string | null;
  "source_project_id": string | null;
  "source_route_id": string | null;
  "status": WebhookDeliveryStatus;
  "attempt_number": number;
  "http_status_code": number | null;
  "duration_ms": number | null;
  "payload": string[];
  "response_body": string | null;
  "response_headers": string[] | null;
  "error_message": string | null;
  "delivered_at": string | null;
  "timestamp": string;
  "sandbox": boolean;
}

export interface WebhookDeliveryListData {
  "id": string;
  "webhook_id": string;
  "event_type": WebhookEvent;
  "source_scope": string | null;
  "source_project_id": string | null;
  "source_route_id": string | null;
  "status": WebhookDeliveryStatus;
  "sandbox": boolean;
  "attempt_number": number;
  "http_status_code": number | null;
  "duration_ms": number | null;
  "delivered_at": string | null;
  "created_at": string;
}

export type WebhookDeliveryStatus = "pending" | "success" | "failed" | "client_error" | "server_error" | "timeout";

export type WebhookEvent = "message.created" | "message.sent" | "message.delivered" | "message.auto_replied" | "message.hard_bounced" | "message.soft_bounced" | "message.spam_complaint" | "message.failed" | "message.suppressed" | "message.unsubscribed" | "message.opened" | "message.clicked" | "message.inbound" | "message.policy_rejected" | "message.scheduled" | "message.rescheduled" | "message.canceled" | "message.released" | "suppression.added" | "suppression.removed" | "webhook.test";

export interface WebhookListData {
  "id": string;
  "scope": WebhookScope;
  "project_ids": (string)[];
  "route_ids": (string)[];
  "route_id": string | null;
  "name": string;
  "url": string;
  "events": (string)[];
  "enabled": boolean;
  "delivery_mode_filter": WebhookDeliveryModeFilter;
  "last_called_at": string | null;
  "created_at": string;
  "updated_at": string;
}

export type WebhookScope = "team" | "project" | "route";

export interface WebhookSecretData {
  "id": string;
  "scope": WebhookScope;
  "project_ids": string[];
  "route_ids": string[];
  "route_id": string | null;
  "name": string;
  "url": string;
  "events": string[];
  "enabled": boolean;
  "include_machine_events": boolean;
  "secret": string;
  "last_called_at": string | null;
  "created_at": string;
  "updated_at": string;
  "delivery_mode_filter": WebhookDeliveryModeFilter;
}

export type DeliveryMode = "live" | "sandbox";

export type WebhookDeliveryModeFilter = "live" | "sandbox" | "both";

export type EmailPayload = SendMailRequest;
export type SendEmailResponse = SendMailResponse;
export type SendBatchEmailResponse = SendBatchMailResponse;
export interface SendMailResponse {
  "message_id": string;
  "status": "pending" | "scheduled";
  "sandbox"?: true;
  "sandbox_result"?: SandboxResult;
  "scheduled_at"?: string;
}

export type SendBatchMailResponse = {
  "message_id": string;
  "status": MessageStatus;
  "scheduled_at"?: string;
  "sandbox"?: true;
  "sandbox_result"?: SandboxResult;
}[];
export type PingResponse = string;
export type DomainIndexResponse = {
  "data": DomainListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type DomainStoreRequest = StoreDomainData;
export type DomainStoreResponse = DomainData;
export type DomainShowResponse = DomainData;
export type DomainDestroyResponse = {
  "message": "Domain deleted successfully.";
};
export type DomainVerifyDnsRecordsResponse = {
  "message": string;
  "recommended_failed_records": {
  "id": string;
  "type": string;
  "name": string;
}[];
};
export type DomainVerifySpecificDnsRecordResponse = {
  "message": "DNS record verified successfully.";
};
export type DomainUpdateProjectsRequest = UpdateDomainProjectsData;
export type DomainUpdateProjectsResponse = {
  "data": DomainData;
  "message": "Domain projects updated successfully.";
};
export type BlockedFileTypesResponse = {
  "extensions": string[];
  "mime_types": string[];
};
export type RescheduleMessageResponse = {
  "message_id": string;
  "status": MessageStatus | null;
  "scheduled_at": string | null;
};
export type MessageShowResponse = MessageData;
export type CancelScheduledMessageResponse = {
  "message_id": string;
  "status": MessageStatus | null;
  "scheduled_at": string | null;
};
export type MessageIndexResponse = {
  "data": MessageListData[];
  "links": string[];
  "meta": {
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_cursor_url": string | null;
  "prev_cursor": string | null;
  "prev_cursor_url": string | null;
};
};
export type MessageEventsResponse = {
  "data": MessageEventData[];
  "links": string[];
  "meta": {
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_cursor_url": string | null;
  "prev_cursor": string | null;
  "prev_cursor_url": string | null;
};
};
export type ProcessInboundMessageResponse = {
  "data": {
  "message_id": string;
  "status": "queued";
  "webhook_target_count": number;
};
};
export type ProjectIndexResponse = {
  "data": ProjectListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type ProjectStoreRequest = StoreProjectData;
export interface ProjectStoreResponse {
  "data": ProjectData;
  "message": string;
  "api_token"?: string;
}

export type ProjectShowResponse = ProjectData;
export type ProjectUpdateRequest = UpdateProjectData;
export type ProjectUpdateResponse = {
  "data": ProjectData;
  "message": "Project updated successfully.";
};
export type ProjectDestroyResponse = {
  "message": "Project deleted successfully.";
};
export type ProjectRotateTokenResponse = {
  "data": ProjectData;
  "new_token": string;
  "message": "API token rotated successfully. Please update your integrations.";
};
export type RouteIndexResponse = {
  "data": RouteListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type RouteStoreRequest = StoreRouteData;
export type RouteStoreResponse = {
  "data": RouteData;
  "message": "Route created successfully.";
};
export type RouteShowResponse = RouteData;
export type RouteUpdateRequest = UpdateRouteData;
export type RouteUpdateResponse = {
  "data": RouteData;
  "message": "Route updated successfully.";
};
export type RouteDestroyResponse = {
  "message": "Route deleted successfully.";
};
export interface RouteVerifyInboundDomainResponse {
  "data": {
  "verified": true;
  "message": "Inbound domain verified successfully.";
};
}

export type StatsIndexResponse = StatsData;
export interface SuppressionIndexResponse {
  "data": (SuppressedRecipientData)[];
  "path": string;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
}

export type SuppressionStoreRequest = StoreSuppressionData;
export type SuppressionStoreResponse = {
  "message": string | "No emails were added.";
  "data": {
  "created": string[];
  "skipped": string[];
};
};
export interface SuppressionDestroyResponse {
  "success": true;
  "status": "removed" | "review_ticket_created" | "review_ticket_exists";
  "message": string;
  "confidence"?: number;
  "ticket_identifier"?: string;
}

export type TeamShowResponse = TeamData;
export type TeamUpdateRequest = UpdateTeamData;
export type TeamUpdateResponse = {
  "data": TeamData;
  "message": "Team settings updated successfully.";
};
export type TeamUsageResponse = TeamUsageDetailData;
export type TeamRolesResponse = {
  "data": TeamRoleData[];
};
export type TeamMembersResponse = {
  "data": TeamMemberData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type TeamMembersShowResponse = TeamMemberData;
export type TeamMembersAssignmentUpdateRequest = UpdateTeamMemberAssignmentData;
export type TeamMembersAssignmentUpdateResponse = TeamMemberData;
export type WebhookIndexResponse = {
  "data": WebhookListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type WebhookStoreRequest = StoreWebhookData;
export type WebhookStoreResponse = {
  "data": WebhookSecretData;
  "message": "Webhook created successfully. Please save the secret as it will not be shown again.";
};
export type WebhookShowResponse = WebhookData;
export type WebhookUpdateRequest = UpdateWebhookData;
export type WebhookUpdateResponse = {
  "data": WebhookData;
  "message": "Webhook updated successfully.";
};
export type WebhookDestroyResponse = {
  "message": "Webhook deleted successfully.";
};
export type WebhookTestResponse = {
  "message": "Test webhook dispatched successfully. Check the deliveries endpoint for results.";
  "delivery_id": string;
};
export type WebhookRegenerateSecretResponse = {
  "data": WebhookSecretData;
  "message": "Webhook secret regenerated successfully. Please update your integration.";
};
export type WebhookDeliveriesResponse = {
  "data": WebhookDeliveryListData[];
  "path": string | null;
  "per_page": number;
  "next_cursor": string | null;
  "next_page_url": string | null;
  "prev_cursor": string | null;
  "prev_page_url": string | null;
};
export type WebhookShowDeliveryResponse = WebhookDeliveryData;

export interface AnalyticsResponseData {
  "data": Record<string, unknown>;
  "meta": Record<string, unknown>;
  "pagination": (string)[];
}

export interface ProjectCreatedData {
  "data": ProjectData;
  "message": string;
  "api_token"?: string;
}

export interface ReportForwardingRequest {
  "destination": string;
}

export interface ReportForwardingResource {
  "destination": string | null;
  "verified": boolean;
  "verified_at": string | null;
}

export interface VerifyReportForwardingRequest {
  "code": string;
}

export interface AnalyticsRequest {
  "metrics": ("accepted" | "processed" | "suppressed" | "policy_rejected" | "application_failed" | "mta_accepted" | "canceled" | "messages" | "delivered" | "bounced" | "soft_bounced" | "administratively_bounced" | "deferred_recipients" | "deferred_events" | "delivery_attempts" | "attempted_recipients" | "transport_outcome_recipients" | "effective_delivered" | "open_tracked_delivered" | "click_tracked_delivered" | "out_of_band_bounced_recipients" | "out_of_band_bounce_events" | "complained" | "unsubscribed" | "human_opens" | "human_opens_events" | "human_clicks" | "human_clicks_events" | "machine_opens" | "machine_opens_events" | "machine_clicks" | "machine_clicks_events" | "privacy_opens" | "privacy_opens_events" | "privacy_clicks" | "privacy_clicks_events" | "bot_opens" | "bot_opens_events" | "bot_clicks" | "bot_clicks_events" | "scanner_opens" | "scanner_opens_events" | "scanner_clicks" | "scanner_clicks_events" | "observed_opens" | "observed_opens_events" | "observed_clicks" | "observed_clicks_events" | "delivery_rate" | "effective_delivery_rate" | "bounce_rate" | "deferral_rate" | "complaint_rate" | "human_open_rate" | "human_click_rate" | "processing_latency_p50_ms" | "processing_latency_p95_ms" | "processing_latency_p99_ms" | "processing_latency_samples" | "delivery_latency_p50_ms" | "delivery_latency_p95_ms" | "delivery_latency_p99_ms" | "delivery_latency_samples" | "total_latency_p50_ms" | "total_latency_p95_ms" | "total_latency_p99_ms" | "total_latency_samples")[];
  "from"?: string;
  "to"?: string;
  "timezone"?: string;
  "include"?: ("summary" | "time_series" | "breakdown")[];
  "group_by"?: (string)[];
  "filters"?: ({
  "dimension": string;
  "operator": "eq" | "in" | "not_in" | "is_null" | "is_not_null";
  "values"?: (string)[];
})[];
  "interval"?: "hour" | "day";
  "compare"?: "previous_period";
  "include_trend"?: boolean;
  "sort"?: {
  "metric": "accepted" | "processed" | "suppressed" | "policy_rejected" | "application_failed" | "mta_accepted" | "canceled" | "messages" | "delivered" | "bounced" | "soft_bounced" | "administratively_bounced" | "deferred_recipients" | "deferred_events" | "delivery_attempts" | "attempted_recipients" | "transport_outcome_recipients" | "effective_delivered" | "open_tracked_delivered" | "click_tracked_delivered" | "out_of_band_bounced_recipients" | "out_of_band_bounce_events" | "complained" | "unsubscribed" | "human_opens" | "human_opens_events" | "human_clicks" | "human_clicks_events" | "machine_opens" | "machine_opens_events" | "machine_clicks" | "machine_clicks_events" | "privacy_opens" | "privacy_opens_events" | "privacy_clicks" | "privacy_clicks_events" | "bot_opens" | "bot_opens_events" | "bot_clicks" | "bot_clicks_events" | "scanner_opens" | "scanner_opens_events" | "scanner_clicks" | "scanner_clicks_events" | "observed_opens" | "observed_opens_events" | "observed_clicks" | "observed_clicks_events" | "delivery_rate" | "effective_delivery_rate" | "bounce_rate" | "deferral_rate" | "complaint_rate" | "human_open_rate" | "human_click_rate" | "processing_latency_p50_ms" | "processing_latency_p95_ms" | "processing_latency_p99_ms" | "processing_latency_samples" | "delivery_latency_p50_ms" | "delivery_latency_p95_ms" | "delivery_latency_p99_ms" | "delivery_latency_samples" | "total_latency_p50_ms" | "total_latency_p95_ms" | "total_latency_p99_ms" | "total_latency_samples";
  "direction": "asc" | "desc";
};
  "limit"?: number;
  "cursor"?: string;
}

export type UpdateReportForwardingRequest = ReportForwardingRequest;

export interface AnalyticsResponse {
  "data": {
  "summary"?: {
  "metrics"?: {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases"?: {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
  "previous"?: {
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
};
  "change"?: Record<string, {
  "absolute"?: number | null;
  "relative"?: number | null;
  "percentage_points"?: number | null;
}>;
};
  "time_series"?: ({
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
  "previous"?: {
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
};
  "change"?: Record<string, {
  "absolute"?: number | null;
  "relative"?: number | null;
  "percentage_points"?: number | null;
}>;
  "from": string;
  "to": string;
  "available": boolean;
  "partial": boolean;
})[];
  "breakdown"?: ({
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
  "previous"?: {
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
};
  "change"?: Record<string, {
  "absolute"?: number | null;
  "relative"?: number | null;
  "percentage_points"?: number | null;
}>;
  "dimensions": Record<string, string | null>;
  "trend"?: ({
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
  "previous"?: {
  "metrics": {
  "accepted"?: number | null;
  "processed"?: number | null;
  "suppressed"?: number | null;
  "policy_rejected"?: number | null;
  "application_failed"?: number | null;
  "mta_accepted"?: number | null;
  "canceled"?: number | null;
  "messages"?: number | null;
  "delivered"?: number | null;
  "bounced"?: number | null;
  "soft_bounced"?: number | null;
  "administratively_bounced"?: number | null;
  "deferred_recipients"?: number | null;
  "deferred_events"?: number | null;
  "delivery_attempts"?: number | null;
  "attempted_recipients"?: number | null;
  "transport_outcome_recipients"?: number | null;
  "effective_delivered"?: number | null;
  "open_tracked_delivered"?: number | null;
  "click_tracked_delivered"?: number | null;
  "out_of_band_bounced_recipients"?: number | null;
  "out_of_band_bounce_events"?: number | null;
  "complained"?: number | null;
  "unsubscribed"?: number | null;
  "human_opens"?: number | null;
  "human_opens_events"?: number | null;
  "human_clicks"?: number | null;
  "human_clicks_events"?: number | null;
  "machine_opens"?: number | null;
  "machine_opens_events"?: number | null;
  "machine_clicks"?: number | null;
  "machine_clicks_events"?: number | null;
  "privacy_opens"?: number | null;
  "privacy_opens_events"?: number | null;
  "privacy_clicks"?: number | null;
  "privacy_clicks_events"?: number | null;
  "bot_opens"?: number | null;
  "bot_opens_events"?: number | null;
  "bot_clicks"?: number | null;
  "bot_clicks_events"?: number | null;
  "scanner_opens"?: number | null;
  "scanner_opens_events"?: number | null;
  "scanner_clicks"?: number | null;
  "scanner_clicks_events"?: number | null;
  "observed_opens"?: number | null;
  "observed_opens_events"?: number | null;
  "observed_clicks"?: number | null;
  "observed_clicks_events"?: number | null;
  "delivery_rate"?: number | null;
  "effective_delivery_rate"?: number | null;
  "bounce_rate"?: number | null;
  "deferral_rate"?: number | null;
  "complaint_rate"?: number | null;
  "human_open_rate"?: number | null;
  "human_click_rate"?: number | null;
  "processing_latency_p50_ms"?: number | null;
  "processing_latency_p95_ms"?: number | null;
  "processing_latency_p99_ms"?: number | null;
  "processing_latency_samples"?: number | null;
  "delivery_latency_p50_ms"?: number | null;
  "delivery_latency_p95_ms"?: number | null;
  "delivery_latency_p99_ms"?: number | null;
  "delivery_latency_samples"?: number | null;
  "total_latency_p50_ms"?: number | null;
  "total_latency_p95_ms"?: number | null;
  "total_latency_p99_ms"?: number | null;
  "total_latency_samples"?: number | null;
};
  "rate_bases": {
  "delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "effective_delivery_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "bounce_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "deferral_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "complaint_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_open_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
  "human_click_rate"?: {
  "numerator": number | null;
  "denominator": number | null;
};
};
};
  "change"?: Record<string, {
  "absolute"?: number | null;
  "relative"?: number | null;
  "percentage_points"?: number | null;
}>;
  "from": string;
  "to": string;
  "available": boolean;
  "partial": boolean;
})[];
})[];
};
  "meta": {
  "time_basis"?: "event";
  "timezone"?: string;
  "interval"?: "hour" | "day";
  "from"?: string;
  "to"?: string;
  "effective_to"?: string;
  "alignment"?: "hour" | "day";
  "generated_at"?: string;
  "available_since"?: string;
  "partial"?: boolean;
  "ongoing"?: boolean;
  "collection_completeness"?: "best_effort";
  "last_ingested_at"?: string | null;
  "metric_definition_version"?: string;
  "ranked_group_limit"?: number;
  "comparison"?: {
  "from": string;
  "to": string;
  "partial": boolean;
};
};
  "pagination": {
  "total_groups": number;
  "returned_groups": number;
  "next_cursor": string | null;
  "truncated": boolean;
};
}

export interface GetReportForwardingResponse {
  "data": ReportForwardingResource;
}

export interface UpdateReportForwardingResponse {
  "data": ReportForwardingResource;
}

export interface VerifyReportForwardingResponse {
  "data": ReportForwardingResource;
}

export interface ResendReportForwardingCodeResponse {
  "data": ReportForwardingResource;
}
